Feature driver or customer
seemir/mydrive pull request #35
Opened 2021-01-16 10:07 UTC by mohammad-usman

Feature is completed.

2021-01-16 10:12 UTC, seemir requested changes

2021-01-16 10:12 UTC, seemir commented on lib/Screens/Roleselector/components/role_ui.dart
> +            height: 5,
du har en `height` definisjon som mangler her

2021-01-17 08:41 UTC, seemir approved these changes

2021-01-17 08:42 UTC, seemir commented
Nå ser ting bra ut 👍 Du kan merge nå du har fikset merge conflictene ☝️

2021-01-21 14:04 UTC, mohammad-usman commented
All view has Welcomescreen as home widget

2021-01-21 14:05 UTC, merged